Layout/LineLength:
  Max: 160

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 55

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 14

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/WordArray:
  Enabled: false
