Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
